import type { BusinessRecord } from "./types";

// CMS-ready seed records for Victor Gbenga Afolabi's business ecosystem.
// Imagery, URLs, metrics, and long-form content can be enriched by a CMS later.
export const businessRecords: BusinessRecord[] = [
  {
    id: "hazon-tech",
    slug: "hazon-tech",
    name: "Hazon Tech",
    category: "technology",
    isPrimaryEcosystem: true,
    parentBusinessSlug: "hazon-holdings",
    tagline: "Technology platforms built for Africa's evolving everyday needs.",
    summary:
      "The technology arm of Hazon Holdings, creating and supporting digital businesses across finance, connectivity, and data.",
    selectorImage: "/images/media/strategy.jpg",
    logoImage: "/images/Business Logos/Hazon Tech Transparent Logo.png",
    heroImage: "/images/BG/Hazon tech BG.png",
    websiteUrl: "https://hazontech.com",
    founder: "Victor Gbenga Afolabi",
    originStory: [
      "Built within Hazon Holdings under Victor Gbenga Afolabi's leadership, Hazon Tech brings software, data engineering and research into one practical technology company.",
      "It exists to help organisations connect their data, decisions and operations through secure, usable digital products.",
    ],
    timeline: [
      { period: "Foundation", title: "A technology arm takes shape", description: "Hazon Holdings created a dedicated home for software, data and research-led solutions." },
      { period: "Expansion", title: "From software to data", description: "The company broadened its work across custom development, analytics and data engineering." },
      { period: "Today", title: "An ecosystem of digital ventures", description: "Hazon Tech supports products across finance, connectivity and retail intelligence." },
    ],
    snapshot: [
      { label: "Industry", value: "Technology" },
      { label: "Location", value: "Lagos, Nigeria" },
      { label: "Focus", value: "Software, data & research" },
      { label: "Ecosystem", value: "Hazon Holdings" },
    ],
    theme: {
      background: "#F7F1E8",
      surface: "#F1E3C1",
      text: "#10204D",
      mutedText: "#6B7280",
      brand: "#D4A51F",
      brandHover: "#B98A12",
      accent: "#0F1C46",
      atmosphere: "rgba(232, 220, 197, 0.62)",
      inactiveDot: "#CFCFD4",
    },
    metrics: [
      { value: "Software", label: "product focus" },
      { value: "Data", label: "core capability" },
      { value: "Research", label: "solutions practice" },
      { value: "Africa", label: "market context" },
    ],
    storySections: [],
    relatedBusinessSlugs: ["flexmonie", "flexmobile", "daggregate"],
  },
  {
    id: "wellness-healthcare",
    slug: "wellness-healthcare",
    name: "Wellness Healthcare",
    category: "healthcare",
    isPrimaryEcosystem: true,
    parentBusinessSlug: "hazon-holdings",
    tagline: "Making quality healthcare more accessible.",
    summary:
      "A healthcare venture within the Hazon ecosystem, focused on services and solutions that support everyday wellbeing.",
    selectorImage: "/images/media/product-lagos.jpg",
    logoImage: "/images/Business Logos/Wellness Transparent Logo.png",
    heroImage: "/images/BG/Wellness BG.png",
    websiteUrl: "https://www.wellnesshealthcare.com.ng",
    founder: "Adetutu Afolabi",
    foundedYear: "2007",
    originStory: [
      "Pharmacist Adetutu Afolabi started Wellness in 2007 as a community pharmacy practice, driven by a belief that dependable healthcare should be easier to reach.",
      "With Victor Gbenga Afolabi serving as Executive Vice Chairman, that foundation has grown into a wider healthcare group spanning pharmacy, health insurance and health technology.",
    ],
    timeline: [
      { period: "2007", title: "A community pharmacy begins", description: "Wellness opened around the need for accessible, everyday care." },
      { period: "2017", title: "Care beyond the counter", description: "Its community work expanded to include continuing free medical care for children at Heritage Homes." },
      { period: "Today", title: "A connected health group", description: "The ecosystem now brings together pharmacy, health insurance, health technology and advocacy." },
    ],
    snapshot: [
      { label: "Industry", value: "Healthcare" },
      { label: "Founded", value: "2007" },
      { label: "Location", value: "Lagos, Nigeria" },
      { label: "Focus", value: "Accessible care" },
    ],
    theme: {
      background: "#F4F6F8",
      surface: "#F7E5B7",
      text: "#1F2E67",
      mutedText: "#667085",
      brand: "#C70E13",
      brandHover: "#A90A10",
      accent: "#1F2E67",
      atmosphere: "rgba(245, 201, 204, 0.62)",
      inactiveDot: "#D3D8E1",
    },
    metrics: [
      { value: "2007", label: "founded" },
      { value: "Healthcare", label: "industry" },
      { value: "Integrated", label: "care model" },
      { value: "Nigeria", label: "market" },
    ],
    storySections: [],
    relatedBusinessSlugs: ["hazon-tech"],
  },
  {
    id: "flexmonie",
    slug: "flexmonie",
    name: "Flexmonie",
    category: "financial-services",
    isPrimaryEcosystem: true,
    parentBusinessSlug: "hazon-tech",
    tagline: "Financial tools designed around everyday mobility.",
    summary:
      "A financial-services business in the Hazon Tech ecosystem.",
    selectorImage: "/images/media/mark-hack.jpg",
    logoImage: "/images/Business Logos/Flexmonie Transparent Logo.png",
    heroImage: "/images/BG/Flexmonie BG.png",
    originStory: [
      "Flexmonie was developed inside the Hazon technology ecosystem to make routine financial tasks feel lighter and more immediate.",
      "The product brings transfers, bill payments and airtime into a mobile experience designed around everyday control.",
    ],
    timeline: [
      { period: "Idea", title: "Finance made flexible", description: "The product vision centred on simplifying the money tasks people repeat every day." },
      { period: "Product", title: "Everyday utility in one place", description: "Transfers, bills and airtime were brought into a single mobile experience." },
      { period: "Today", title: "Part of Hazon Tech", description: "Flexmonie continues as a financial-services venture within the wider technology ecosystem." },
    ],
    snapshot: [
      { label: "Industry", value: "Financial services" },
      { label: "Location", value: "Nigeria" },
      { label: "Focus", value: "Payments & everyday money" },
      { label: "Ecosystem", value: "Hazon Tech" },
    ],
    theme: {
      background: "#F7F4FC",
      surface: "#EFE7FC",
      text: "#2D1782",
      mutedText: "#667085",
      brand: "#9727E8",
      brandHover: "#6F1DCE",
      accent: "#251A77",
      atmosphere: "rgba(230, 215, 251, 0.7)",
      inactiveDot: "#D7D0E5",
    },
    metrics: [
      { value: "Payments", label: "product focus" },
      { value: "Mobile-first", label: "experience" },
      { value: "Everyday", label: "utility" },
      { value: "Hazon Tech", label: "ecosystem" },
    ],
    storySections: [],
    relatedBusinessSlugs: ["hazon-tech", "flexmobile", "daggregate"],
  },
  {
    id: "flexmobile",
    slug: "flexmobile",
    name: "Flexmobile",
    category: "telecommunications",
    isPrimaryEcosystem: true,
    parentBusinessSlug: "hazon-tech",
    tagline: "Connectivity and mobility for a more connected Africa.",
    summary:
      "A telecommunications business in the Hazon Tech ecosystem.",
    selectorImage: "/images/media/strategy.jpg",
    logoImage: "/images/Business Logos/Flex Mobile Transparent Logo.png",
    heroImage: "/images/BG/Flex mobile BG.png",
    websiteUrl: "https://flexmobile.com.ng",
    founder: "Hazon Technologies",
    originStory: [
      "Flexmobile was created by Hazon Technologies as a digital-first mobile virtual network operator for the way Nigerians live, work and move.",
      "Years of planning focused the service on flexibility, customer control and an app-first experience rather than rigid, one-size-fits-all connectivity.",
    ],
    timeline: [
      { period: "Build", title: "The foundation comes first", description: "The team developed its operating model, partnerships and supporting infrastructure." },
      { period: "2026", title: "Preparing for market entry", description: "Commercial partnerships and a network agreement positioned Flexmobile for its Nigerian debut." },
      { period: "Today", title: "Your network, your rules", description: "The platform brings connectivity, self-service and flexible plans into one digital experience." },
    ],
    snapshot: [
      { label: "Industry", value: "Telecommunications" },
      { label: "Location", value: "Lagos, Nigeria" },
      { label: "Model", value: "Digital-first MVNO" },
      { label: "Ecosystem", value: "Hazon Tech" },
    ],
    theme: {
      background: "#F7F4FC",
      surface: "#EEE6FB",
      text: "#3C136B",
      mutedText: "#667085",
      brand: "#B12EF4",
      brandHover: "#9324D2",
      accent: "#43136F",
      atmosphere: "rgba(234, 216, 250, 0.72)",
      inactiveDot: "#D8D0E3",
    },
    metrics: [
      { value: "MVNO", label: "operating model" },
      { value: "Digital-first", label: "experience" },
      { value: "Nigeria", label: "market" },
      { value: "Hazon Tech", label: "ecosystem" },
    ],
    storySections: [],
    relatedBusinessSlugs: ["hazon-tech", "flexmonie", "daggregate"],
  },
  {
    id: "daggregate",
    slug: "daggregate",
    name: "D'Aggregate",
    category: "data-platform",
    isPrimaryEcosystem: true,
    parentBusinessSlug: "hazon-tech",
    tagline: "Data infrastructure that makes better decisions possible.",
    summary:
      "A data-platform business in the Hazon Tech ecosystem.",
    selectorImage: "/images/media/product-lagos.jpg",
    logoImage: "/images/Business Logos/DAggregate Transparent Logo.png",
    heroImage: "/images/BG/DAggregate BG.png",
    websiteUrl: "http://d-aggregate.com",
    foundedYear: "2022",
    originStory: [
      "D'Aggregate was founded in 2022 to close the visibility gap between organisations and the realities of last-mile markets.",
      "Its field network turns on-ground market activity into actionable data for retail execution, research and better business decisions.",
    ],
    timeline: [
      { period: "2022", title: "The data network begins", description: "D'Aggregate launched around data collection, analytics and market intelligence." },
      { period: "Scale", title: "A wider field network", description: "Its aggregator community expanded across Nigeria and other West African markets." },
      { period: "Today", title: "Retail intelligence in action", description: "The platform supports consumer insight, retail audits and field-force management." },
    ],
    snapshot: [
      { label: "Industry", value: "Data & retail technology" },
      { label: "Founded", value: "2022" },
      { label: "Location", value: "Lagos, Nigeria" },
      { label: "Focus", value: "Last-mile intelligence" },
    ],
    theme: {
      background: "#F5FBFB",
      surface: "#C8F1E4",
      text: "#0A1F63",
      mutedText: "#667085",
      brand: "#14A86B",
      brandHover: "#0F8E5A",
      accent: "#082E6B",
      atmosphere: "rgba(221, 244, 238, 0.72)",
      inactiveDot: "#C9CED8",
    },
    metrics: [
      { value: "2022", label: "founded" },
      { value: "Retail", label: "market focus" },
      { value: "Data", label: "core capability" },
      { value: "West Africa", label: "reach" },
    ],
    storySections: [],
    relatedBusinessSlugs: ["hazon-tech", "flexmonie", "flexmobile"],
  },
  {
    id: "gdm-group",
    slug: "gdm-group",
    name: "GDM Group",
    category: "marketing-and-communications",
    isPrimaryEcosystem: true,
    tagline: "Building brands, experiences, and systems that move markets.",
    summary:
      "A marketing and communications group creating strategic work for brands and organisations across Africa.",
    selectorImage: "/images/about/business.jpg",
    logoImage: "/images/Business Logos/GDM Transparent Logo.png",
    heroImage: "/images/BG/GDM BG.png",
    websiteUrl: "https://gdmgroup.com.ng",
    founder: "Victor Gbenga Afolabi",
    foundedYear: "2009",
    originStory: [
      "Victor Gbenga Afolabi began GDM in 2009 with a focused ambition: help brands generate demand and connect meaningfully with consumers.",
      "What began as an experiential agency evolved into a full-service marketing, management and technology group serving brands across Nigeria and West Africa.",
    ],
    timeline: [
      { period: "2009", title: "Generating demand", description: "GDM began its journey as an experiential marketing business." },
      { period: "2015", title: "Connecting brands at scale", description: "A first rebrand marked wider capacity and operations across Nigeria." },
      { period: "2022—24", title: "The transition into technology", description: "Proprietary tools and data capability expanded the group's offer." },
      { period: "Today", title: "Marketing. Management. Technology.", description: "GDM operates as an integrated partner to organisations across West Africa." },
    ],
    snapshot: [
      { label: "Industry", value: "Marketing & media technology" },
      { label: "Founded", value: "2009" },
      { label: "Reach", value: "Nigeria & West Africa" },
      { label: "Portfolio", value: "207+ brands" },
    ],
    theme: {
      background: "#160304",
      surface: "#1A0304",
      text: "#FFFFFF",
      mutedText: "#E6DDDB",
      brand: "#C3113F",
      brandHover: "#960B2D",
      accent: "#A71977",
      atmosphere: "rgba(58, 10, 18, 0.72)",
      inactiveDot: "#8C8587",
    },
    metrics: [
      { value: "2009", label: "founded" },
      { value: "207+", label: "brands in portfolio" },
      { value: "600", label: "projects annually" },
      { value: "West Africa", label: "reach" },
    ],
    storySections: [],
    relatedBusinessSlugs: ["eko-innovation-centre", "art-of-technology-lagos"],
  },
  {
    id: "eko-innovation-centre",
    slug: "eko-innovation-centre",
    name: "Eko Innovation Centre",
    category: "innovation-ecosystem",
    isPrimaryEcosystem: true,
    tagline: "A platform for the people and ideas shaping Africa's future.",
    summary:
      "An innovation ecosystem connecting founders, institutions, and communities working on meaningful progress.",
    selectorImage: "/images/media/product-lagos.jpg",
    logoImage: "/images/Business Logos/EIC Transparent Logo.png",
    heroImage: "/images/BG/EIC BG.png",
    websiteUrl: "https://ekoicentre.com",
    founder: "Victor Gbenga Afolabi",
    foundedYear: "2019",
    originStory: [
      "Victor Gbenga Afolabi established Eko Innovation Centre to close practical gaps in funding, mentorship and commercialisation for technology-led ventures.",
      "Unveiled in Lagos in 2019, the centre was built as a launchpad where founders, institutions and public partners could turn ideas into scalable impact.",
    ],
    timeline: [
      { period: "2019", title: "Unveiled in Lagos", description: "Eko Innovation Centre opened as a platform for technology-led enterprise." },
      { period: "Programmes", title: "Ideas meet opportunity", description: "Hackathons, incubation, acceleration and learning programmes created pathways to market." },
      { period: "Today", title: "Innovation at ecosystem scale", description: "The centre continues to connect startups with expertise, partners and capital." },
    ],
    snapshot: [
      { label: "Industry", value: "Innovation ecosystem" },
      { label: "Founded", value: "2019" },
      { label: "Location", value: "Lagos, Nigeria" },
      { label: "Focus", value: "Accelerate & commercialise" },
    ],
    metrics: [
      { value: "2019", label: "founded" },
      { value: "6,000+", label: "startup entries" },
      { value: "4,500+", label: "people trained" },
      { value: "40+", label: "startups supported" },
    ],
    theme: {
      background: "#001B44",
      surface: "#001233",
      text: "#FFFFFF",
      mutedText: "#CDD6E8",
      brand: "#0D4DFF",
      brandHover: "#003CCF",
      accent: "#2B7BFF",
      atmosphere: "rgba(14, 61, 154, 0.62)",
      inactiveDot: "#97A3B6",
    },
    storySections: [],
    relatedBusinessSlugs: ["gdm-group", "art-of-technology-lagos"],
  },
  {
    id: "art-of-technology-lagos",
    slug: "art-of-technology-lagos",
    name: "Art of Technology Lagos",
    category: "industry-initiative",
    isPrimaryEcosystem: true,
    tagline: "Conversations, connections, and momentum for the future of technology.",
    summary:
      "A future-facing technology platform convening the people, ideas, and partnerships shaping Lagos and Africa.",
    selectorImage: "/images/media/strategy.jpg",
    logoImage: "/images/Business Logos/AOT Transparent Logo.png",
    heroImage: "/images/BG/AOT BG.png",
    websiteUrl: "https://aotlagos.com",
    founder: "Victor Gbenga Afolabi",
    foundedYear: "2019",
    originStory: [
      "Curated by Victor Gbenga Afolabi through Eko Innovation Centre, Art of Technology Lagos began in 2019 as a Lagos State-powered meeting point for technology and public policy.",
      "It exists to bring government, enterprise, founders and the wider technology community into the same room to shape a smarter, more inclusive Lagos.",
    ],
    timeline: [
      { period: "2019", title: "AOT Lagos 1.0", description: "The first edition convened more than 2,000 participants around a smarter, digital Lagos." },
      { period: "2022", title: "Talent acceleration", description: "AOT 4.0 widened the conversation to talent sustainability and ecosystem awards." },
      { period: "2023", title: "A global audience", description: "The fifth edition reached participants across 141 countries and six continents." },
      { period: "Today", title: "Technology, policy and society", description: "AOT continues to convene the people shaping responsible technology adoption." },
    ],
    snapshot: [
      { label: "Format", value: "Technology conference" },
      { label: "First edition", value: "2019" },
      { label: "Location", value: "Lagos, Nigeria" },
      { label: "Focus", value: "Policy, innovation & technology" },
    ],
    theme: {
      background: "#F5F7F8",
      surface: "#F6E5BE",
      text: "#0E1833",
      mutedText: "#667085",
      brand: "#FF5A5F",
      brandHover: "#F0444D",
      accent: "#63B7C3",
      atmosphere: "rgba(245, 201, 197, 0.7)",
      inactiveDot: "#CFCFD4",
    },
    metrics: [
      { value: "2019", label: "first edition" },
      { value: "2,000+", label: "maiden participants" },
      { value: "141", label: "countries reached" },
      { value: "6", label: "continents reached" },
    ],
    storySections: [],
    relatedBusinessSlugs: ["gdm-group", "eko-innovation-centre"],
  },
];
